/**
 * Datos físicos de cada escena simulada. Los valores de luminancia (EV100) siguen tablas
 * estándar de exposición: sol pleno ≈ 15, sombra/nublado ≈ 12–13, golden hour ≈ 11–12,
 * bosque en sombra densa ≈ 9–10, avenida iluminada de noche ≈ 4 y cielo con Vía Láctea ≈ −7.
 */
import type { SceneId, SimScene } from './types';

const t = (denominator: number) => Math.pow(2, -Math.round(3 * Math.log2(denominator)) / 3);
const n = (nominal: number) => Math.pow(2, Math.round(6 * Math.log2(nominal)) / 6);
const sec = (s: number) => Math.pow(2, Math.round(3 * Math.log2(s)) / 3);

export const SCENES: Record<SceneId, SimScene> = {
  plaza: {
    id: 'plaza',
    name: 'Plaza al caer la tarde',
    description: 'Un ciclista cruza frente a unas luces colgantes. Ideal para ver a la vez desenfoque de fondo, barrido de movimiento y ruido.',
    subjectLabel: 'Ciclista',
    lighting: {
      ev100: 11,
      illuminantK: 5000,
      subjectDistanceM: 6,
      subjectSpeedMS: 5,
      backgroundDistanceM: 40,
      foregroundDistanceM: 1.6,
      meteringBias: { matrix: 0, center: 0.3, spot: 0 },
      sceneContrastStops: 10,
      hasStars: false,
    },
    refFocalMm: 35,
    focalRange: [24, 135],
    defaults: { focalMm: 50, focusM: 6, aperture: n(4), shutter: t(250), iso: 200, wbK: 5000 },
  },
  'golden-hour-portrait': {
    id: 'golden-hour-portrait',
    name: 'Retrato en la hora dorada',
    description: 'Contraluz cálido al atardecer. El exposímetro matricial se deja engañar por el cielo brillante.',
    subjectLabel: 'Rostro de la persona',
    lighting: {
      ev100: 11,
      illuminantK: 3500,
      subjectDistanceM: 3,
      subjectSpeedMS: 0.2,
      backgroundDistanceM: 20,
      foregroundDistanceM: null,
      meteringBias: { matrix: 1.0, center: 0.7, spot: 0 },
      sceneContrastStops: 12,
      hasStars: false,
    },
    refFocalMm: 85,
    focalRange: [35, 200],
    defaults: { focalMm: 85, focusM: 3, aperture: n(8), shutter: t(250), iso: 100, wbK: 5500 },
  },
  'sports-action': {
    id: 'sports-action',
    name: 'Deporte con cielo nublado',
    description: 'Un jugador corre a toda velocidad bajo un cielo nublado brillante. Para congelarlo hace falta una velocidad de obturación muy alta.',
    subjectLabel: 'Jugador',
    lighting: {
      ev100: 13,
      illuminantK: 6500,
      subjectDistanceM: 20,
      subjectSpeedMS: 8,
      backgroundDistanceM: 50,
      foregroundDistanceM: null,
      meteringBias: { matrix: 0, center: 0, spot: 0 },
      sceneContrastStops: 9,
      hasStars: false,
    },
    refFocalMm: 200,
    focalRange: [70, 600],
    defaults: { focalMm: 200, focusM: 20, aperture: n(8), shutter: t(60), iso: 100, wbK: 5500 },
  },
  landscape: {
    id: 'landscape',
    name: 'Paisaje de montaña',
    description: 'Rocas en primer plano, un lago y montañas lejanas. El reto es tener todo nítido.',
    subjectLabel: 'Rocas del primer plano',
    lighting: {
      ev100: 13,
      illuminantK: 5200,
      subjectDistanceM: 3,
      subjectSpeedMS: 0,
      backgroundDistanceM: 2000,
      foregroundDistanceM: 1.5,
      meteringBias: { matrix: 0, center: 0.3, spot: 0 },
      sceneContrastStops: 11,
      hasStars: false,
    },
    refFocalMm: 24,
    focalRange: [14, 70],
    defaults: { focalMm: 24, focusM: 3, aperture: n(2.8), shutter: t(1000), iso: 400, wbK: 5200 },
  },
  astro: {
    id: 'astro',
    name: 'Vía Láctea',
    description: 'Cielo oscuro con la Vía Láctea sobre un árbol. Exposiciones largas, ISO alto y la regla de los 500.',
    subjectLabel: 'Estrellas',
    lighting: {
      ev100: -7,
      illuminantK: 4000,
      subjectDistanceM: 1_000_000,
      subjectSpeedMS: 0,
      backgroundDistanceM: 1_000_000,
      foregroundDistanceM: 15,
      meteringBias: { matrix: -0.7, center: -0.3, spot: 0 },
      sceneContrastStops: 8,
      hasStars: true,
    },
    refFocalMm: 20,
    focalRange: [14, 50],
    defaults: { focalMm: 20, focusM: 1_000_000, aperture: n(5.6), shutter: sec(2), iso: 800, wbK: 5500 },
  },
  street: {
    id: 'street',
    name: 'Calle de la ciudad',
    description: 'Peatones caminando en una calle en sombra. Enfoque por zona y una velocidad segura.',
    subjectLabel: 'Peatón',
    lighting: {
      ev100: 12,
      illuminantK: 6500,
      subjectDistanceM: 3,
      subjectSpeedMS: 1.4,
      backgroundDistanceM: 15,
      foregroundDistanceM: null,
      meteringBias: { matrix: 0, center: 0, spot: 0.3 },
      sceneContrastStops: 10,
      hasStars: false,
    },
    refFocalMm: 35,
    focalRange: [24, 85],
    defaults: { focalMm: 35, focusM: 3, aperture: n(2), shutter: t(60), iso: 100, wbK: 5500 },
  },
  waterfall: {
    id: 'waterfall',
    name: 'Cascada en el bosque',
    description: 'Agua cayendo entre rocas en la sombra densa del bosque en un día nublado. Con exposiciones largas el agua se vuelve seda.',
    subjectLabel: 'Caída de agua',
    lighting: {
      ev100: 9,
      illuminantK: 6500,
      subjectDistanceM: 8,
      subjectSpeedMS: 4,
      backgroundDistanceM: 20,
      foregroundDistanceM: 2,
      meteringBias: { matrix: 0.3, center: 0.3, spot: 0.7 },
      sceneContrastStops: 9,
      hasStars: false,
    },
    refFocalMm: 28,
    focalRange: [16, 70],
    defaults: { focalMm: 28, focusM: 8, aperture: n(4), shutter: t(500), iso: 400, wbK: 5500 },
  },
  'night-city': {
    id: 'night-city',
    name: 'Ciudad de noche',
    description: 'Autos pasando por una avenida iluminada. Larga exposición para dibujar estelas de luz.',
    subjectLabel: 'Autos',
    lighting: {
      ev100: 5,
      illuminantK: 3300,
      subjectDistanceM: 15,
      subjectSpeedMS: 12,
      backgroundDistanceM: 90,
      foregroundDistanceM: null,
      meteringBias: { matrix: -0.7, center: -0.3, spot: 0.7 },
      sceneContrastStops: 14,
      hasStars: false,
    },
    refFocalMm: 35,
    focalRange: [24, 85],
    defaults: { focalMm: 35, focusM: 15, aperture: n(4), shutter: t(60), iso: 1600, wbK: 5500 },
  },
  studio: {
    id: 'studio',
    name: 'Estudio con luz continua',
    description: 'Retrato y producto bajo paneles LED continuos. La luz está controlada: el reto es la nitidez, la profundidad de campo y la calidad de imagen.',
    subjectLabel: 'Rostro / producto',
    lighting: {
      ev100: 9,
      illuminantK: 5600,
      subjectDistanceM: 1.5,
      subjectSpeedMS: 0,
      backgroundDistanceM: 3,
      foregroundDistanceM: null,
      meteringBias: { matrix: 0, center: 0, spot: 0 },
      sceneContrastStops: 7,
      hasStars: false,
    },
    refFocalMm: 85,
    focalRange: [35, 135],
    defaults: { focalMm: 85, focusM: 1.5, aperture: n(2.8), shutter: t(125), iso: 400, wbK: 5600 },
  },
};

export const SCENE_LIST: SimScene[] = Object.values(SCENES);
